version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: drocsid-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    networks:
      - drocsid-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  registry-service:
    build:
      context: .
      dockerfile: Dockerfile.registry
    container_name: drocsid-registry
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5261
    ports:
      - "5261:5261"
    volumes:
      - ./registry-appsettings.json:/app/appsettings.json
    networks:
      - drocsid-network
    restart: on-failure

  api-node-1:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: drocsid-api-1
    depends_on:
      registry-service:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5186
    ports:
      - "5186:5186"
    volumes:
      - ./node1-appsettings.json:/app/appsettings.json
      - api-node1-storage:/app/FileStorage
    networks:
      - drocsid-network
    restart: on-failure

  api-node-2:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: drocsid-api-2
    depends_on:
      registry-service:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5186
    ports:
      - "5187:5186"
    volumes:
      - ./node2-appsettings.json:/app/appsettings.json
      - api-node2-storage:/app/FileStorage
    networks:
      - drocsid-network
    restart: on-failure

  api-node-3:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: drocsid-api-3
    depends_on:
      registry-service:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5186
    ports:
      - "5188:5186"
    volumes:
      - ./node3-appsettings.json:/app/appsettings.json
      - api-node3-storage:/app/FileStorage
    networks:
      - drocsid-network
    restart: on-failure

networks:
  drocsid-network:
    driver: bridge

volumes:
  postgres-data:
  api-node1-storage:
  api-node2-storage:
  api-node3-storage: